name: zenon_syrius_wallet_flutter
description: Zenon cross-platform non-custodial wallet
version: 0.0.6
publish_to: none

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  fl_chart: ^0.60.0
  overlay_support: ^2.1.0
  lottie: ^2.1.0
  dotted_border: ^2.0.0+2
  flutter_svg: ^2.0.0+1
  flutter_vector_icons: ^2.0.0
  expandable: ^5.0.1
  marquee_widget: ^1.2.0
  layout: ^1.0.2
  flutter_staggered_grid_view: 0.4.0
  flip_card: ^0.7.0
  auto_size_text: ^3.0.0
  window_manager: ^0.3.0
  stacked: ^3.1.2
  path_provider: ^2.0.8
  rxdart: ^0.27.3
  hive: ^2.0.5
  url_launcher: ^6.0.18
  provider: ^6.0.2
  intl: ^0.18.0
  package_info_plus: ^3.0.2
  device_info_plus: ^8.0.0
  infinite_scroll_pagination: ^3.1.0
  share_plus: ^6.3.0
  page_transition: ^2.0.4
  file_selector: ^0.9.2+2
  pretty_qr_code: ^2.0.3
  screenshot: ^1.3.0
  desktop_drop: ^0.4.0
  validators: ^3.0.0
  wakelock: ^0.6.1+2
  number_selector: ^1.0.5
  znn_sdk_dart:
    git:
      url: https://github.com/sol-sanctum/znn_sdk_dart.git
      ref: spork_htlc
  json_rpc_2: ^3.0.2
  path: ^1.8.2
  ffi: ^2.0.1
  get_it: ^7.2.0
  hex: ^0.2.0
  local_notifier: ^0.1.5
  tray_manager: ^0.2.0
  open_filex: ^4.3.2
  launch_at_startup: ^0.2.1
  logging: ^1.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.7
  hive_generator: ^2.0.0
  flutter_lints: ^2.0.1
  dependency_validator: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/i18n/
    - assets/lottie/
    - assets/svg/